export const validationSchema = {
    "id": {
        name: 'ID',
        placeholder: 'Ingrese el ID',
        id: 'id',
        type: 'number',
        required: false,
        visible: false,
        minLength: 0,
        maxLength: 10,
        min: undefined,
        max: undefined,
        pattern: undefined,
        size: undefined,
        select: undefined,
        multiple: undefined,
        rows: undefined,
        cols: undefined,
        email: undefined
    },
    "firstName": {
        name: 'Nombres',
        placeholder: '',
        id: 'firstName',
        type: 'text',
        required: true,
        visible: true,
        minLength: 1,
        maxLength: 100,
        min: undefined,
        max: undefined,
        pattern: undefined,
        size: undefined,
        select: undefined,
        multiple: undefined,
        rows: undefined,
        cols: undefined,
        email: undefined
    },
    "lastName": {
        name: 'Apellidos',
        placeholder: '',
        id: 'lastName',
        type: 'text',
        required: true,
        minLength: 1,
        maxLength: 100,
        min: undefined,
        max: undefined,
        pattern: undefined,
        size: undefined,
        select: undefined,
        multiple: undefined,
        rows: undefined,
        cols: undefined,
        email: undefined
    },
    "documentTypeId": {
        name: 'Tipo de documento',
        placeholder: undefined,
        id: 'documentTypeId',
        type: 'text',
        required: false,
        minLength: 0,
        maxLength: 5,
        min: undefined,
        max: undefined,
        pattern: undefined,
        size: undefined,
        select: true,
        multiple: undefined,
        rows: undefined,
        cols: undefined,
        email: undefined
    },
    "documentNumber": {
        name: 'Número de documento',
        placeholder: undefined,
        id: 'documentNumber',
        type: 'text',
        required: false,
        minLength: 0,
        maxLength: 25,
        min: undefined,
        max: undefined,
        pattern: undefined,
        size: undefined,
        select: undefined,
        multiple: undefined,
        rows: undefined,
        cols: undefined,
        email: undefined
    },
    "genderId": {
        name: 'Género',
        placeholder: undefined,
        id: 'genderId',
        type: 'text',
        required: false,
        minLength: 0,
        maxLength: 5,
        min: undefined,
        max: undefined,
        pattern: undefined,
        size: undefined,
        select: true,
        multiple: undefined,
        rows: undefined,
        cols: undefined,
        email: undefined
    },
    "nationalityId": {
        name: 'Nacionalidad',
        placeholder: undefined,
        id: 'nationalityId',
        type: 'text',
        required: false,
        minLength: 0,
        maxLength: 5,
        min: undefined,
        max: undefined,
        pattern: undefined,
        size: undefined,
        select: true,
        multiple: undefined,
        rows: undefined,
        cols: undefined,
        email: undefined
    },

    "birthdate": {
        name: 'Fecha de nacimiento',
        placeholder: undefined,
        id: 'birthdate',
        type: 'date',
        required: false,
        minLength: 0,
        maxLength: 19,
        min: undefined,
        max: undefined,
        pattern: undefined,
        size: undefined,
        select: undefined,
        multiple: undefined,
        rows: undefined,
        cols: undefined,
        email: undefined
    },
    "maritalStatusId": {
        name: 'Estado civil',
        placeholder: undefined,
        id: 'maritalStatusId',
        type: 'text',
        required: false,
        minLength: 0,
        maxLength: 5,
        min: undefined,
        max: undefined,
        pattern: undefined,
        size: undefined,
        select: true,
        multiple: undefined,
        rows: undefined,
        cols: undefined,
        email: undefined
    },
    "statusId": {
        name: 'Estado',
        placeholder: undefined,
        id: 'statusId',
        type: 'text',
        required: false,
        minLength: 0,
        maxLength: 5,
        min: undefined,
        max: undefined,
        pattern: undefined,
        size: undefined,
        select: true,
        multiple: undefined,
        rows: undefined,
        cols: undefined,
        email: undefined
    },

    "createdAt": {
        name: 'createdAt',
        placeholder: undefined,
        id: 'createdAt',
        type: 'datetime-local',
        required: false,
        minLength: 0,
        maxLength: 24,
        min: undefined,
        max: undefined,
        pattern: undefined,
        size: undefined,
        select: undefined,
        multiple: undefined,
        rows: undefined,
        cols: undefined,
        email: undefined
    },


    "contactInformation": {
        "email": {
            name: 'Correo electrónico',
            placeholder: "Ejemplo: correo@example.com",
            id: 'email',
            type: 'email',
            required: false,
            minLength: 0,
            maxLength: 100,
            min: undefined,
            max: undefined,
            pattern: undefined,
            size: undefined,
            select: undefined,
            multiple: undefined,
            rows: undefined,
            cols: undefined,
            email: true
        },
        "phone": {
            name: 'Teléfono',
            placeholder: "Ejemplo: +573105397777",
            id: 'phone',
            type: 'text',
            required: false,
            minLength: 0,
            maxLength: 15,
            min: undefined,
            max: undefined,
            pattern: undefined,
            size: undefined,
            select: undefined,
            multiple: undefined,
            rows: undefined,
            cols: undefined,
            email: undefined
        },
        "address": {
            name: 'Dirección',
            placeholder: "Ejemplo: Calle 1#1-25",
            id: 'address',
            type: 'text',
            required: false,
            minLength: 0,
            maxLength: 100,
            min: undefined,
            max: undefined,
            pattern: undefined,
            size: undefined,
            select: undefined,
            multiple: undefined,
            rows: undefined,
            cols: undefined,
            email: undefined
        },
        "corporateEmail": {
            name: 'Correo corporativo',
            placeholder: "Ejemplo: correo@example.com",
            id: 'corporateEmail',
            type: 'email',
            required: false,
            minLength: 0,
            maxLength: 100,
            min: undefined,
            max: undefined,
            pattern: undefined,
            size: undefined,
            select: undefined,
            multiple: undefined,
            rows: undefined,
            cols: undefined,
            email: undefined
        },
    },
    "employmentInformation": {
        "position": {
            name: 'Cargo o posición',
            placeholder: undefined,
            id: 'position',
            type: 'text',
            required: false,
            minLength: 0,
            maxLength: 75,
            min: undefined,
            max: undefined,
            pattern: undefined,
            size: undefined,
            select: undefined,
            multiple: undefined,
            rows: undefined,
            cols: undefined,
            email: undefined
        },
        "department": {
            name: 'Departamento o área',
            placeholder: undefined,
            id: 'department',
            type: 'text',
            required: false,
            minLength: 0,
            maxLength: 75,
            min: undefined,
            max: undefined,
            pattern: undefined,
            size: undefined,
            select: undefined,
            multiple: undefined,
            rows: undefined,
            cols: undefined,
            email: undefined
        },
        "dateHiring": {
            name: 'Fecha de contratación',
            placeholder: undefined,
            id: 'dateHiring',
            type: 'date',
            required: false,
            minLength: 0,
            maxLength: 19,
            min: undefined,
            max: undefined,
            pattern: undefined,
            size: undefined,
            select: undefined,
            multiple: undefined,
            rows: undefined,
            cols: undefined,
            email: undefined
        },
        "typeContractId": {
            name: 'Tipo de contrato',
            placeholder: undefined,
            id: 'typeContractId',
            type: 'text',
            required: false,
            minLength: 0,
            maxLength: 5,
            min: undefined,
            max: undefined,
            pattern: undefined,
            size: undefined,
            select: true,
            multiple: undefined,
            rows: undefined,
            cols: undefined,
            email: undefined
        },
        "directBoss": {
            name: 'Jefe directo',
            placeholder: undefined,
            id: 'directBoss',
            type: 'text',
            required: false,
            minLength: 0,
            maxLength: 100,
            min: undefined,
            max: undefined,
            pattern: undefined,
            size: undefined,
            select: undefined,
            multiple: undefined,
            rows: undefined,
            cols: undefined,
            email: undefined
        },
    },
    "bankingInformation": {
        "bankAccountNumber": {
            name: 'bankAccountNumber',
            placeholder: undefined,
            id: 'bankAccountNumber',
            type: 'text',
            required: false,
            minLength: 0,
            maxLength: 20,
            min: undefined,
            max: undefined,
            pattern: undefined,
            size: undefined,
            select: undefined,
            multiple: undefined,
            rows: undefined,
            cols: undefined,
            email: undefined
        },
        "bankId": {
            name: 'bankId',
            placeholder: undefined,
            id: 'bankId',
            type: 'text',
            required: false,
            minLength: 0,
            maxLength: 5,
            min: undefined,
            max: undefined,
            pattern: undefined,
            size: undefined,
            select: true,
            multiple: undefined,
            rows: undefined,
            cols: undefined,
            email: undefined
        },
        "accountTypeId": {
            name: 'accountTypeId',
            placeholder: undefined,
            id: 'accountTypeId',
            type: 'text',
            required: false,
            minLength: 0,
            maxLength: 5,
            min: undefined,
            max: undefined,
            pattern: undefined,
            size: undefined,
            select: true,
            multiple: undefined,
            rows: undefined,
            cols: undefined,
            email: undefined
        },
    },
    "additionalInformation": {
        "description": {
            name: 'description',
            placeholder: undefined,
            id: 'description',
            type: 'text',
            required: false,
            minLength: 0,
            maxLength: 200,
            min: undefined,
            max: undefined,
            pattern: undefined,
            size: undefined,
            select: undefined,
            multiple: undefined,
            rows: undefined,
            cols: undefined,
            email: undefined
        },
    }

};