export const validationSchema = {
    "id": {
        name: 'ID',
        placeholder: '',
        id: 'id',
        type: 'number',
        required: false,
        visible: false,
        minLength: 0,
        maxLength: 10,
        min: undefined,
        max: undefined,
        pattern: undefined,
        size: undefined,
        select: undefined,
        multiple: undefined,
        rows: undefined,
        cols: undefined,
        email: undefined
    },
    "firstName": {
        name: 'Nombres',
        placeholder: '',
        id: 'firstName',
        type: 'text',
        required: true,
        visible: true,
        minLength: 1,
        maxLength: 100,
        min: undefined,
        max: undefined,
        pattern: undefined,
        size: undefined,
        select: undefined,
        multiple: undefined,
        rows: undefined,
        cols: undefined,
        email: undefined
    },
    "lastName": {
        name: 'Apellidos',
        placeholder: '',
        id: 'lastName',
        type: 'text',
        required: true,
        minLength: 1,
        maxLength: 100,
        min: undefined,
        max: undefined,
        pattern: undefined,
        size: undefined,
        select: undefined,
        multiple: undefined,
        rows: undefined,
        cols: undefined,
        email: undefined
    },
    "documentTypeId": {
        name: 'Tipo de documento',
        placeholder: undefined,
        id: 'documentTypeId',
        type: 'text',
        required: false,
        minLength: 0,
        maxLength: 5,
        min: undefined,
        max: undefined,
        pattern: undefined,
        size: undefined,
        select: true,
        multiple: undefined,
        rows: undefined,
        cols: undefined,
        email: undefined
    },
    "documentNumber": {
        name: 'Número de documento',
        placeholder: undefined,
        id: 'documentNumber',
        type: 'text',
        required: false,
        minLength: 0,
        maxLength: 20,
        min: undefined,
        max: undefined,
        pattern: undefined,
        size: undefined,
        select: undefined,
        multiple: undefined,
        rows: undefined,
        cols: undefined,
        email: undefined
    },
    "genderId": {
        name: 'Género',
        placeholder: undefined,
        id: 'genderId',
        type: 'text',
        required: false,
        minLength: 0,
        maxLength: 5,
        min: undefined,
        max: undefined,
        pattern: undefined,
        size: undefined,
        select: true,
        multiple: undefined,
        rows: undefined,
        cols: undefined,
        email: undefined
    },
    "nationalityId": {
        name: 'Nacionalidad',
        placeholder: undefined,
        id: 'nationalityId',
        type: 'text',
        required: false,
        minLength: 0,
        maxLength: 5,
        min: undefined,
        max: undefined,
        pattern: undefined,
        size: undefined,
        select: true,
        multiple: undefined,
        rows: undefined,
        cols: undefined,
        email: undefined
    },

    "birthdate": {
        name: 'Fecha de nacimiento',
        placeholder: undefined,
        id: 'birthdate',
        type: 'date',
        required: false,
        minLength: 0,
        maxLength: 19,
        min: undefined,
        max: undefined,
        pattern: undefined,
        size: undefined,
        select: undefined,
        multiple: undefined,
        rows: undefined,
        cols: undefined,
        email: undefined
    },
    "statusId": {
        name: 'Estado',
        placeholder: undefined,
        id: 'statusId',
        type: 'text',
        required: true,
        minLength: 0,
        maxLength: 5,
        min: undefined,
        max: undefined,
        pattern: undefined,
        size: undefined,
        select: true,
        multiple: undefined,
        rows: undefined,
        cols: undefined,
        email: undefined
    },
    "createdAt": {
        name: 'createdAt',
        placeholder: undefined,
        id: 'createdAt',
        type: 'datetime-local',
        required: false,
        minLength: 0,
        maxLength: 24,
        min: undefined,
        max: undefined,
        pattern: undefined,
        size: undefined,
        select: undefined,
        multiple: undefined,
        rows: undefined,
        cols: undefined,
        email: undefined
    },
    "contactInformation": {
        "email": {
            name: 'Correo electrónico',
            placeholder: "Ejemplo: correo@example.com",
            id: 'email',
            type: 'email',
            required: false,
            minLength: 0,
            maxLength: 100,
            min: undefined,
            max: undefined,
            pattern: undefined,
            size: undefined,
            select: undefined,
            multiple: undefined,
            rows: undefined,
            cols: undefined,
            email: true
        },
        "phone": {
            name: 'Teléfono',
            placeholder: "Ejemplo: +573105397777",
            id: 'phone',
            type: 'text',
            required: false,
            minLength: 0,
            maxLength: 15,
            min: undefined,
            max: undefined,
            pattern: /^(\+57|57)?[1-9]\d{9}$/,
            size: undefined,
            select: undefined,
            multiple: undefined,
            rows: undefined,
            cols: undefined,
            email: undefined
        },
        "address": {
            name: 'Dirección',
            placeholder: "Ejemplo: Calle 1#1-25",
            id: 'address',
            type: 'text',
            required: false,
            minLength: 0,
            maxLength: 100,
            min: undefined,
            max: undefined,
            pattern: undefined,
            size: undefined,
            select: undefined,
            multiple: undefined,
            rows: undefined,
            cols: undefined,
            email: undefined
        },
    },
    "segmentationAndTags": {
        "customerTypeId": {
            name: 'Tipo de cliente',
            placeholder: undefined,
            id: 'customerTypeId',
            type: 'text',
            required: false,
            minLength: 0,
            maxLength: 5,
            min: undefined,
            max: undefined,
            pattern: undefined,
            size: undefined,
            select: true,
            multiple: undefined,
            rows: undefined,
            cols: undefined,
            email: undefined
        },
        "customerTags": {
            name: 'Etiquetas',
            placeholder: "Ejemplo: Cliente con descuento especial",
            id: 'customerTags',
            type: 'text',
            required: false,
            minLength: 0,
            maxLength: 100,
            min: undefined,
            max: undefined,
            pattern: undefined,
            size: undefined,
            select: false,
            multiple: undefined,
            rows: undefined,
            cols: undefined,
            email: undefined,
            isArray: true
        }
    },
    "preferences": {
        "communicationChannel": {
            name: 'Canal de comunicación preferido',
            placeholder: undefined,
            id: 'bankAccountNumber',
            type: 'text',
            required: false,
            minLength: 0,
            maxLength: 100,
            min: undefined,
            max: undefined,
            pattern: undefined,
            size: undefined,
            select: undefined,
            multiple: undefined,
            rows: undefined,
            cols: undefined,
            email: undefined
        },
        "acceptPromotions": {
            name: 'Acepta envío de promociones',
            placeholder: undefined,
            id: 'acceptPromotions',
            type: 'text',
            required: false,
            minLength: 0,
            maxLength: 5,
            min: undefined,
            max: undefined,
            pattern: undefined,
            size: undefined,
            select: true,
            multiple: undefined,
            rows: undefined,
            cols: undefined,
            email: undefined
        },
        "favoriteCategories": {
            name: 'Categorías favoritas',
            placeholder: undefined,
            id: 'favoriteCategories',
            type: 'text',
            required: false,
            minLength: 0,
            maxLength: 5,
            min: undefined,
            max: undefined,
            pattern: undefined,
            size: undefined,
            select: true,
            multiple: undefined,
            rows: undefined,
            cols: undefined,
            email: undefined
        },
    },
    "additionalInformation": {
        "description": {
            name: 'Descripción',
            placeholder: undefined,
            id: 'description',
            type: 'text',
            required: false,
            minLength: 0,
            maxLength: 200,
            min: undefined,
            max: undefined,
            pattern: undefined,
            size: undefined,
            select: undefined,
            multiple: undefined,
            rows: undefined,
            cols: undefined,
            email: undefined
        },
    }

};